api_platform:
    # Global behaviour for collection
    collection:
        # Pagination settings: https://api-platform.com/docs/core/pagination/#pagination
        pagination:
            client_enabled: false
            client_items_per_page: true
            client_partial: true
            enabled: true
            enabled_parameter_name: _pagination
            items_per_page: 5
            items_per_page_parameter_name: _itemsPerPage
            maximum_items_per_page: 20
            page_parameter_name: _page
            partial: false
            partial_parameter_name: _partial
        order_parameter_name: '_order'
    exception_to_status:
        App\Exception\EmptyBodyException: 400
    mapping:
        paths:
            - '%kernel.project_dir%/src/Entity' # default configuration for annotations
            - '%kernel.project_dir%/config/api_platform' # yaml or xml directory configuration
            - '%kernel.project_dir%/config/api_platform/resources' # Custom yaml entity configuration
    patch_formats:
        json: ['application/merge-patch+json']

    swagger:
        versions: [3]
