api_platform:
    # Global behaviour for collection
    collection:
        pagination:
#            enabled: false
            page_parameter_name: _page
#        order_parameter_name: '_order'

    mapping:
        paths:
            - '%kernel.project_dir%/src/Entity' # default configuration for annotations
            - '%kernel.project_dir%/config/api_platform' # yaml or xml directory configuration
            - '%kernel.project_dir%/config/api_platform/resources' # Custom yaml entity configuration
    patch_formats:
        json: ['application/merge-patch+json']

    swagger:
        versions: [3]
