vich_uploader:
    db_driver: orm

    mappings:
        images:
            uri_prefix: /uploads/images
            upload_destination: '%kernel.project_dir%/public/uploads/images'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
#        profile_image:
#            uri_prefix: /uploads/images
#            upload_destination: '%kernel.project_dir%/public/uploads'
#            namer: Vich\UploaderBundle\Naming\UniqidNamer
