version: "3.2"

networks:
  webnetwork:
    external: true

services:
  fakemail:
    command:
      - bin/maildev
      - --web
      - "80"
      - --smtp
      - "1025"
    container_name: fakemail
    image: djfarrelly/maildev
    labels:
      traefik.enable: true
      traefik.docker.network: webnetwork
      traefik.http.routers.fakemail.rule: Host(`post-fakemail.dev.it`)
      traefik.http.services.fakemail.loadbalancer.server.port: 80
    networks:
      - webnetwork
      - default
    ports:
      - 1025:25
  nginx:
    container_name: nginx
    command: [nginx-debug, '-g', 'daemon off;']
    depends_on:
      - php
    image: nginx:latest
    links:
      - php
    labels:
      traefik.enable: true
      traefik.docker.network: webnetwork
      traefik.http.routers.nginx.rule: Host(`post-api.dev.it`)
#      traefik.http.routers.nginx.entrypoints: web
      traefik.http.services.nginx.loadbalancer.server.port: 80
    networks:
      - webnetwork
      - default
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/remote.conf:/etc/nginx/xdebugremote.conf:ro
      - ./public:/var/www/html/public:ro
  traefik:
    container_name: traefik
    image: traefik:v2.0
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - 80:80
      - 8080:8080
    networks:
      - webnetwork
      - default
    volumes:
#      - ./docker/traefik/traefik.yml:/etc/traefik/traefik.yml
      - /var/run/docker.sock:/var/run/docker.sock
  php:
    build:
      args:
        - CUSTOM_USER_ID=${USER_ID}
        - CUSTOM_USER_GROUP=${USER_GROUP}
      dockerfile: Dockerfile
      context: .
    container_name: php
    env_file:
      - .env.local
    networks:
      - webnetwork
      - default
    volumes:
      - ./docker/php/zz-apcu.ini:/usr/local/etc/php/conf.d/zz-apcu.ini:ro
      - ./docker/php/zz-php.ini:/usr/local/etc/php/conf.d/zz-php.ini:ro
      - ./docker/php/zz-xdebug.ini:/usr/local/etc/php/conf.d/zz-xdebug.ini:ro
      - .:/var/www/html:cached
