App\Entity\BlogPost:
  attributes:
    normalization_context:
      groups:
        - 'get-blog-post-with-author'
    denormalization_context:
      groups:
        - 'post'
  collectionOperations:
    get:
      method: 'GET'
    post:
      access_control: "is_granted('ROLE_WRITER')"
  itemOperations:
    get:
      method: 'GET'
    put:
      access_control: "is_granted('ROLE_EDITOR') or (is_granted('ROLE_WRITER') and object.getAuthor() == user)"
      access_control_message: "Sorry, but you are not the actual blog post owner."
  properties:
    comments:
      subresource:
        resourceClass: 'App\Entity\Comment'
        collection: true