App\Entity\BlogPost:
  attributes:
    denormalization_context:
      groups:
        - 'post'
    normalization_context:
      groups:
        - 'get-blog-post-with-author'
    order:
      published: 'DESC'
  collectionOperations:
    get:
      method: 'GET'
      filters:
        - 'app.blog.date_filter'
        - 'app.blog.order_filter'
        - 'app.blog.property_filter'
        - 'app.blog.range_filter'
        - 'app.blog.search_filter'
    post:
      access_control: "is_granted('ROLE_WRITER')"
  itemOperations:
    get:
      method: 'GET'
    put:
      method: 'PUT'
      security: "is_granted('ROLE_EDITOR') or (is_granted('ROLE_WRITER') and object.getAuthor() == user)"
      security_message: "Sorry, but you are not the actual blog post owner."
  properties:
    comments:
      subresource:
        resourceClass: 'App\Entity\Comment'
        collection: true
    images:
      subresource:
        resourceClass: 'App\Entity\Image'
        collection: true