App\Entity\Comment:
  attributes:
      denormalization_context:
        groups:
          - 'post'
  itemOperations:
    get:
      method: 'GET'
    put:
      access_control: "is_granted('ROLE_EDITOR') or (is_granted('ROLE_COMMENTATOR') and object.getAuthor() == user)"
      access_control_message: "Sorry, but you are not the actual comment owner."
      normalization_context:
        groups:
          - 'post'
  collectionOperations:
    get:
      method: 'GET'
    post:
      access_control: "is_granted('ROLE_COMMENTATOR')"
      normalization_context:
        groups:
          - 'post'
  subresourceOperations:
    api_blog_posts_comments_get_subresource:
      normalization_context:
        groups:
          - 'get-comment-with-author'