App\Entity\Comment:
  attributes:
      denormalization_context:
        groups:
          - 'post'
      order:
        published: 'DESC'
      pagination_enabled: false
      pagination_client_enabled: true
      pagination_client_items_per_page: true
      pagination_partial: true
      maximum_items_per_page: 30

  itemOperations:
    get:
      method: 'GET'
    put:
      security: "is_granted('ROLE_EDITOR') or (is_granted('ROLE_COMMENTATOR') and object.getAuthor() == user)"
      security_message: "Sorry, but you are not the actual comment owner."
      normalization_context:
        groups:
          - 'post'
  collectionOperations:
    get:
      method: 'GET'
    post:
      security: "is_granted('ROLE_COMMENTATOR')"
      normalization_context:
        groups:
          - 'post'
  subresourceOperations:
    api_blog_posts_comments_get_subresource:
      normalization_context:
        groups:
          - 'get-comment-with-author'