App\Entity\Image:
  attributes:
    order:
      id: 'DESC'
  collectionOperations:
    get:
      method: 'GET'
    post:
      access_control: "is_granted('ROLE_WRITER')"
      method: 'POST'
      path: '/images'
      controller: App\Controller\UploadImageAction
      defaults:
        _api_receive: false