easy_admin:
    entities:
        BlogPost:
            class: App\Entity\BlogPost
            label: 'admin.blog_post.name'
            list:
                actions:
                    - { name: 'show', label: 'admin.action.show' }
            show:
                fields:
                    - id
                    - title
                    - published
                    - { property: 'comments', template: 'easy_admin/BlogPost/comments.html.twig' }
                    - images