easy_admin:
    entities:
        Image:
            class: App\Entity\Image
            list:
                fields:
                    - id
                    - {property: 'url', type: 'image', label: 'Image'}
            form:
                fields:
                    - {property: 'file', type: 'Vich\UploaderBundle\Form\Type\VichFileType'}