## static configuration
# traefik.yml

entryPoints:
  web:
    address: ":80"

# Docker configuration backend
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"

# API and dashboard configuration
api:
  insecure: true

##---------------------##

## dynamic configuration
# dynamic-conf.yml

